[project]
name = "geobot"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Dorian Vuk", email = "vuk.dorian@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.5.0",
    "faiss-cpu>=1.13.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "timm>=1.0.24",
    "torch>=2.3.0",
    "torchvision>=0.18.0",
    "tqdm>=4.67.1",
    "transformers>=5.0.0",
]

[project.scripts]
geobot = "geobot:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.14",
]
